<a href="https://colab.research.google.com/github/amosweckstrom/neural_networks/blob/main/mnist_neural_network_0_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

A neural network for predicting handwritten numbers from the famous MNIST dataset. Truly a work of art.



In a world of numbers, both bold and fine,\
I ventured forth to make them mine.\
With TensorFlow's might and Pandas' grace,\
I sought to teach a neural embrace.

In [39]:
import tensorflow as tf
import pandas as pd
import numpy as np
from tensorflow.keras.layers import Dense
from tensorflow.keras.losses import BinaryCrossentropy
from tensorflow.keras import Sequential

In [40]:
mnist_train = pd.read_csv("./sample_data/mnist_train_small.csv")
mnist_test = pd.read_csv("./sample_data/mnist_test.csv")

In [41]:
mnist_train.head(5)

6  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.581  0.582  0.583  \
0  5  0    0    0    0    0    0    0    0    0  ...      0      0      0   
1  7  0    0    0    0    0    0    0    0    0  ...      0      0      0   
2  9  0    0    0    0    0    0    0    0    0  ...      0      0      0   
3  5  0    0    0    0    0    0    0    0    0  ...      0      0      0   
4  2  0    0    0    0    0    0    0    0    0  ...      0      0      0   

   0.584  0.585  0.586  0.587  0.588  0.589  0.590  
0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0  

[5 rows x 785 columns]

In [42]:
X_train = mnist_train.drop("6", axis=1)
y_train = pd.get_dummies(mnist_train["6"])


In [43]:
print(
    "Shape of training feature data: ", X_train.shape,
    "\nShape of training target data: ", y_train.shape
)

y_train.head(5)

Shape of training feature data:  (19999, 784) 
Shape of training target data:  (19999, 10)


0  1  2  3  4  5  6  7  8  9
0  0  0  0  0  0  1  0  0  0  0
1  0  0  0  0  0  0  0  1  0  0
2  0  0  0  0  0  0  0  0  0  1
3  0  0  0  0  0  1  0  0  0  0
4  0  0  1  0  0  0  0  0  0  0

In [44]:
X_test = mnist_test.drop("7", axis=1)
y_test = pd.get_dummies(mnist_test["7"])

From CSVs the numbers rise,\
Transformed, they become the network's prize.\
Dropping columns, one-hot encode,\
Preparing data, ready for the road.

In [45]:
print(
    "Shape of test feature data: ", X_test.shape,
    "\nShape of test target data: ", y_test.shape
)

Shape of test feature data:  (9999, 784) 
Shape of test target data:  (9999, 10)


In layers deep and activation strong,\
The network learned right from wrong.\
Sigmoid whispers in every neuron's ear,\
Guiding them, making the path clear.

In [46]:
model = Sequential([
    Dense(25, activation="sigmoid"),
    Dense(15, activation="sigmoid"),
    Dense(10, activation="sigmoid")
])

model.compile(loss=BinaryCrossentropy())

Layers dense, like a thinker's thought,\
Each neuron with wisdom fraught.\
Binary crossentropy, loss's guide,\
Optimizing with a steady stride.

In [47]:
model.fit(X_train, y_train, epochs=50)

Epoch 1/50
625/625 [==============================] - 2s 2ms/step - loss: 0.3356
Epoch 2/50
625/625 [==============================] - 1s 2ms/step - loss: 0.2084
Epoch 3/50
625/625 [==============================] - 1s 2ms/step - loss: 0.1512
Epoch 4/50
625/625 [==============================] - 2s 3ms/step - loss: 0.1204
Epoch 5/50
625/625 [==============================] - 2s 3ms/step - loss: 0.1032
Epoch 6/50
625/625 [==============================] - 1s 2ms/step - loss: 0.0936
Epoch 7/50
625/625 [==============================] - 1s 2ms/step - loss: 0.0856
Epoch 8/50
625/625 [==============================] - 1s 2ms/step - loss: 0.0796
Epoch 9/50
625/625 [==============================] - 1s 2ms/step - loss: 0.0769
Epoch 10/50
625/625 [==============================] - 1s 2ms/step - loss: 0.0741
Epoch 11/50
625/625 [==============================] - 1s 2ms/step - loss: 0.0711
Epoch 12/50
625/625 [==============================] - 1s 2ms/step - loss: 0.0697
Epoch 13/50
625/625 [====

Epochs fifty, patience's test,\
In the forge of learning, never at rest.\
Predictions bloom like spring's first flower,\
Awaiting judgment in their final hour.

In [48]:
predictions = model.predict(X_test)

313/313 [==============================] - 1s 2ms/step


In [49]:
def max_to_one(array):
    # Step 1: Find the maximum value in each row
    row_maxes = array.max(axis=1).reshape(-1, 1)

    # Step 2: Create a boolean mask
    bool_mask = (array == row_maxes)

    # Step 3: Convert the boolean mask to integers
    return bool_mask.astype(int)

In [50]:
binary_predictions = max_to_one(predictions)

In [51]:
print(binary_predictions)

[[0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [52]:
pred_df = pd.DataFrame(binary_predictions)

Comparing predicted with the true,\
Correct or not? Insights anew.\
Accuracy speaks, a tale of trial,\
In numbers' dance, a reason to smile.

In [53]:
predicted_classes = pred_df.idxmax(axis=1)
actual_classes = y_test.idxmax(axis=1)

correct_predictions = (predicted_classes == actual_classes)

accuracy = correct_predictions.mean()
print(f'Accuracy: {accuracy:.2f}')


Accuracy: 0.91


Ninety-one percent, the network's song,\
In the realm of digits, where it belongs.\
A journey of bytes, of tensors' play,\
In the art of learning, a bright new day.

So here I stand, with code my quill,\
A digital bard on an endless hill.\
Through TensorFlow's lens, the world's a little clearer,\
The beauty of neural networks, ever nearer.